server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    freemarker:
      cache: false
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
