package com.example.chat.domain.mock;

import com.example.chat.domain.member.domain.Member;
import com.example.chat.domain.member.service.port.MemberRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class FakeMemberRepository implements MemberRepository {
    private Long autoGeneratedId = 0L;
    private final List<Member> store = new ArrayList<>();

    @Override
    public Optional<Member> findById(Long id) {
        return store.stream().filter(member -> Objects.equals(member.getId(), id)).findAny();
    }

    @Override
    public Optional<Member> findByName(String name) {
        return store.stream().filter(member -> Objects.equals(member.getName(), name)).findAny();
    }

    @Override
    public Member save(Member member) {
        Member newMember = Member.builder()
                .id(++autoGeneratedId)
                .name(member.getName())
                .nickname(member.getNickname())
                .build();

        store.add(newMember);
        return newMember;
    }
}
